### ISSUE TITLE
fosphor_nvidia_gpu  version 3.8

### ISSUE THREAD

**Issue by catalinalb** [paulgclark/grc-install#3]
Hello,

I did run the script for installing gnuradio and hackrf everything good. :)

The only problem is when I did run the script for fosphor_nvidia_gpu 

Building dependency tree       
Reading state information... Done
clinfo is already the newest version (2.2.18.03.26-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fatal: destination path 'gr-fosphor' already exists and is not an empty directory.
sed: can't read gr-fosphor/grc/fosphor_qt_sink_c.xml: No such file or directory
mkdir: cannot create directory ‘build’: File exists
-- Build type not specified: defaulting to release.
CMake Error at CMakeLists.txt:46 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.8".

  The following configuration files were considered but not accepted:

    /home/ctl/install/sdr/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.7.13.5

-- Configuring incomplete, errors occurred!
See also "/home/ctl/install/src/gr-fosphor/build/CMakeFiles/CMakeOutput.log".
CMake Error: Cannot open file for write: /home/ctl/install/src/gr-fosphor/build/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. /home/ctl/install/src/gr-fosphor/build/CMakeCache.txt
CMake Error: : System Error: Permission denied
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
ctl@xps:~/install/grc-install/install_scripts$

**Comment by paulgclark** [comment]
I'm sorry, I should take the Nvidia version of this script out of the repo. I haven't had a chance to debug it yet. The Intel version works now with gnuradio 3.8, but that's about it currently.

**Comment by catalinalb** [comment]
Ok Thank you for your answer. Great Job. I finally was able to install Gnu Radio with osmocom and qt with your support. I don't need 3.8 I just want the 3.7 release with fosphor. I will try the intel version on a different machine. 
Thank you

**Comment by paulgclark** [comment]
I prefer to use 3.7 right now as well, but it is possible to install both on your system. Simply comment out the line in your ~/.bashrc that sources setup_env.sh and reinstall with a different path like this:
sudo ./grc_from_source.sh 3.8 ~/install_38

You can then use 3.8 just to run fosphor and switch back to the old setup_env.sh to run 3.7.

**Comment by catalinalb** [comment]
Hi I did try to install both versions and still, fosphor didn´t know where to find the 3.8. So I just deleted everything and started new. I did install 3.7 with hackrf and the rf-tools also I did run the fosphor nvidia script until the point where it gave me the 3.8 error. Then I went to: install/src and deleted gr-fosphor folder. 
git clone https://github.com/osmocom/gr-fosphor.git
cd into gr-fosphor
git checkout -b gr3.7 origin/gr3.7
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/home/ctl/install/sdr   (*ctl is my user)
make
sudo make install
sudo ldconfig

Now I was able to find fosphor in gnuradio-companion and olso the osmocom_fft -F tried to start still the OPENCL drivers were missing. I did install them and now everything works. ... with intel gpu not with nvidia. 

I have to say I managed all this with the help from the gnuradio Slack members. 

Before all this, I did try to run the fosphor for intel GPU but it didn´t recognize any intel GPU on my maschine. I run a DELL xps L702x with an old angry nvidia GPU and 3GB of video memory but I have to use it´s intel GPU ..... 

I hope this can help you edit / update the installation scripts. It would be nice if you can add gqrx and gr-gsm with it´s problematic gr-iqbal.

Anyway, thank you and good job!!

**Comment by catalinalb** [comment]
it seems like I was able to add gr-gsm with the same method. It works like a charm. No errors. 

cd install/src
git clone https://git.osmocom.org/gr-gsm
cd gr-gsm
mkdir build
cmake .. -DCMAKE_INSTALL_PREFIX=/home/ctl/install/sdr
make
sudo make install
sudo ldconfig


Running happy with Hackrf One :)

**Comment by paulgclark** [comment]
Awesome! Thanks for the hints on fosphor+gr37, I'll try to incorporate them into the script.

**Comment by paulgclark** [comment]
Update: fosphor_intel_gpu.sh install script has been fixed to work on both 3.7 and 3.8

**Comment by catalinalb** [comment]
Yes I used it yesterday and it worked without any problems.

Can you fix the one for nvidia as well?

I try to install gqrx now a bit of a new territory since I have to use qmake and it requires Qt5.

Thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by catalinalb** [comment]
OK... maybe this is off-topic now. (let me know where to write it...)
So I added gqrx and is running great. Here is what I have done:

sudo apt-get install libqt5opengl5-dev libqt5svg5-dev qt5-default (thank's to the instructions received from Mr. Vasil Velichkov)
git clone https://github.com/csete/gqrx.git gqrx.git
cd gqrx.git
mkdir build
cd build
qmake ..
make
sudo make install
sudo ldconfig

I am working now on installing qspectrumanalyzer for hackrf.

keep you posted!

**Comment by catalinalb** [comment]
Details for qspectrumanalyzer:
git clone https://github.com/xmikos/qspectrumanalyzer.git
cd qspectrumanalyzer
pip3 install --user .
sudo python3 setup.py install

then just cd and run it with qspectrumanalyzer. Works!

**Comment by paulgclark** [comment]
If you have a new script you'd like added, please create a new issue so we I can track them a little easier.

Thanks, by the way for contributing. This is awesome stuff!

**Comment by paulgclark** [comment]
PS I just created new issues for the two you mentioned. I'll probably create a subdirectory off the main install to start putting these into.
