### ISSUE TITLE
Add modules from Dr. Bastian Bloessl: gr-foo, gr-ieee802-11, gr-ieee802-15-4

### ISSUE THREAD

**Issue by catalinalb** [paulgclark/grc-install#8]
On ubuntu 18.04 LTS after installing GNU-Radio 3.7, gqrx, gr-fosphor, qspectrumanalyzer, wireshark, gr-gsm and binwalk:

- **installing gr-foo**
cd install/src
git clone https://github.com/bastibl/gr-foo.git
cd gr-foo
git checkout maint-3.7
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/home/ctl/install/sdr (where ctl is my username)
make
sudo make install
sudo ldconfig
cd

- **installing gr-ieee802-11**
cd install/src
git clone git://github.com/bastibl/gr-ieee802-11.git
cd gr-ieee802-11
git checkout maint-3.7
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/home/ctl/install/sdr (where ctl is my username)
make
sudo make install
sudo ldconfig
sudo sysctl -w kernel.shmmax=2147483648
cd

- **installing gr-ieee802-15-4 - ZigBee**
sudo apt-get install python-matplotlib
cd install/src
git clone https://github.com/bastibl/gr-ieee802-15-4.git
cd gr-ieee802-15-4
git checkout maint-3.7
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/home/ctl/install/sdr (where ctl is my username)
make
sudo make install
sudo ldconfig
cd

More info:
https://www.bastibl.net/

**Comment by paulgclark** [comment]
Script has been committed:
grc-install/install_scripts/oot/bastibl_from_source.sh

I don't know enough to test, but I did see one of the example flowgraphs is missing a block:
gr-ieee802-15-4/examples/transceiver_CSS_loopback.grc

Any ideas?

**Comment by paulgclark** [comment]
Ahh... never mind. There was a hier block in there I had to generate first. Seems to run now. Still haven't learned how to use it yet...

**Comment by paulgclark** [comment]
Seems to work
